# Generated by Django 2.2.7 on 2019-12-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twtr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
