# Generated by Django 2.2.7 on 2019-12-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twtr', '0003_auto_20191212_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='created_at',
            new_name='created',
        ),
    ]
