# Generated by Django 2.2.7 on 2019-12-12 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twtr', '0005_auto_20191212_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('author', 'target')},
        ),
    ]
